cmake_minimum_required(VERSION 3.20)
# Exercise the actual version resolver with cache-style and CI environment inputs.
foreach(case IN ITEMS cache empty_environment ci_environment prefixed)
    unset(ENV{BRANCH})
    unset(ENV{BUILD_VERSION})
    set(BUILD_VERSION "1.19.0-beta.5")
    set(expected "1.19.0-beta.5")
    if(case STREQUAL "empty_environment")
        set(ENV{BUILD_VERSION} "")
    elseif(case STREQUAL "ci_environment")
        set(ENV{BUILD_VERSION} "1.19.1-beta.1")
        set(expected "1.19.1-beta.1")
    elseif(case STREQUAL "prefixed")
        set(BUILD_VERSION "v1.19.0-beta.5")
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/prep/build_version.cmake")
    if(NOT PROJECT_VERSION_FULL STREQUAL expected)
        message(FATAL_ERROR "${case}: expected ${expected}, got ${PROJECT_VERSION_FULL}")
    endif()
endforeach()
